name: mhealthgoal
description: "App that collects EF, ER, and physical activity data for scientific research."
publish_to: "none"
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  cht_cognition:
    path: ../../packages/cht_cognition
  firebase_core: ^4.7.0
  firebase_messaging: ^16.2.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^20.1.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  go_router: ^17.2.3
  intl: any
  pedometer: ^4.2.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.5
  json_serializable: ^6.13.2

flutter:
  uses-material-design: true
  generate: true
