name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

template: |
  ## Changes
  $CHANGES

  ## Contributors
  $CONTRIBUTORS

categories:
  # ================================
  # 📦 cht_ema_cognitive_tasks
  # ================================
  - title: "## 📦 cht_ema_cognitive_tasks — 🚀 Features"
    labels: [pkg:cognitive-tasks, feature]

  - title: "## 📦 cht_ema_cognitive_tasks — 🐞 Fixes"
    labels: [pkg:cognitive-tasks, fix]

  - title: "## 📦 cht_ema_cognitive_tasks — 🧪 Tests"
    labels: [pkg:cognitive-tasks, test]

  - title: "## 📦 cht_ema_cognitive_tasks — 🛠️ Improvements / Refactors"
    labels: [pkg:cognitive-tasks, improvement, refactor]

  - title: "## 📦 cht_ema_cognitive_tasks — 📚 Documentation"
    labels: [pkg:cognitive-tasks, docs]

  - title: "## 📦 cht_ema_cognitive_tasks — ⚙️ CI / Chores / Deps"
    labels: [pkg:cognitive-tasks, ci, chore, dependencies]

  # ================================
  # 📦 cht_ema_surveys
  # ================================
  - title: "## 📦 cht_ema_surveys — 🚀 Features"
    labels: [pkg:surveys, feature]

  - title: "## 📦 cht_ema_surveys — 🐞 Fixes"
    labels: [pkg:surveys, fix]

  - title: "## 📦 cht_ema_surveys — 🧪 Tests"
    labels: [pkg:surveys, test]

  - title: "## 📦 cht_ema_surveys — 🛠️ Improvements / Refactors"
    labels: [pkg:surveys, improvement, refactor]

  - title: "## 📦 cht_ema_surveys — 📚 Documentation"
    labels: [pkg:surveys, docs]

  - title: "## 📦 cht_ema_surveys — ⚙️ CI / Chores / Deps"
    labels: [pkg:surveys, ci, chore, dependencies]

change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"

exclude-labels:
  - skip-changelog
  - wip

version-resolver:
  major:
    labels: [breaking, "semver:major"]
  minor:
    labels: [feature, "semver:minor"]
  patch:
    labels:
      - fix
      - test
      - documentation
      - refactor
      - improvement
      - ci
      - chore
      - dependencies
      - "semver:patch"
  default: patch

autolabeler:
  - label: feature
    title:
      - "/^(feat|feature)\\b/i"

  - label: fix
    title:
      - "/^(fix|bug)\\b/i"

  - label: test
    title:
      - "/^(tests?)\\b/i"

  - label: documentation
    title:
      - "/^(docs?|documentation)\\b/i"

  - label: refactor
    title:
      - "/^(refactor)\\b/i"

  - label: improvement
    title:
      - "/^(improve|improvement)\\b/i"

  - label: ci
    title:
      - "/^(ci)\\b/i"

  - label: chore
    title:
      - "/^(chore)\\b/i"

  - label: dependencies
    title:
      - "/^(deps?|dependencies)\\b/i"

  - label: pkg:cognitive-tasks
    files:
      - "packages/cht_ema_cognitive_tasks/**"

  - label: pkg:surveys
    files:
      - "packages/cht_ema_surveys/**"
