name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

template: |
  ## Changes
  $CHANGES

  ## Contributors
  $CONTRIBUTORS

categories:
  # ================================
  # 📦 cht_ema_cognitive_tasks
  # ================================
  - title: "## 📦 cht_ema_cognitive_tasks — 🚀 Features"
    labels: [pkg:cognitive-tasks, feature]

  - title: "## 📦 cht_ema_cognitive_tasks — 🐞 Fixes"
    labels: [pkg:cognitive-tasks, bug]

  - title: "## 📦 cht_ema_cognitive_tasks — 🧪 Tests"
    labels: [pkg:cognitive-tasks, test]

  - title: "## 📦 cht_ema_cognitive_tasks — 🛠️ Improvements / Refactors"
    labels: [pkg:cognitive-tasks, enhancement, enh, refactor, performance, perf]

  - title: "## 📦 cht_ema_cognitive_tasks — 📚 Documentation"
    labels: [pkg:cognitive-tasks, documentation, docs]

  - title: "## 📦 cht_ema_cognitive_tasks — ⚙️ CI / Chores / Deps"
    labels: [pkg:cognitive-tasks, ci, chore, dependencies, deps]

  # ================================
  # 📦 cht_ema_surveys
  # ================================
  - title: "## 📦 cht_ema_surveys — 🚀 Features"
    labels: [pkg:surveys, feature]

  - title: "## 📦 cht_ema_surveys — 🐞 Fixes"
    labels: [pkg:surveys, bug]

  - title: "## 📦 cht_ema_surveys — 🧪 Tests"
    labels: [pkg:surveys, test]

  - title: "## 📦 cht_ema_surveys — 🛠️ Improvements / Refactors"
    labels: [pkg:surveys, enhancement, enh, refactor, performance, perf]

  - title: "## 📦 cht_ema_surveys — 📚 Documentation"
    labels: [pkg:surveys, documentation, docs]

  - title: "## 📦 cht_ema_surveys — ⚙️ CI / Chores / Deps"
    labels: [pkg:surveys, ci, chore, dependencies, deps]

change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"

exclude-labels:
  - skip-changelog
  - wip

version-resolver:
  major:
    labels: [breaking, "semver:major"]
  minor:
    labels: [feature, "semver:minor"]
  patch:
    labels:
      - bug
      - enhancement
      - enh
      - refactor
      - documentation
      - docs
      - ci
      - chore
      - dependencies
      - deps
      - test
      - performance
      - perf
      - "semver:patch"
  default: patch

autolabeler:
  - label: dependencies
    title:
      - '/^chore\\(deps\\)/i'
      - "/^deps?:/i"
    files:
      - "pubspec.yaml"
      - "**/Podfile*"
      - "android/**/build.gradle*"
  - label: bug
    title:
      - "/^(fix|bug)/i"
  - label: feature
    title:
      - "/^(feat|feature)/i"
  - label: documentation
    title:
      - "/^(docs?|doc)/i"
    files:
      - "README.md"
      - "docs/**"
      - "example/**"
  - label: performance
    title:
      - "/^(perf|performance)/i"
  - label: ci
    files:
      - ".github/**"
      - "tool/**"
  - label: pkg:cognitive-tasks
    files:
      - "packages/cht_ema_cognitive_tasks/**"
  - label: pkg:surveys
    files:
      - "packages/cht_ema_surveys/**"
