name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

template: |
  ## Changes
  $CHANGES

  ## Contributors
  $CONTRIBUTORS

categories:
  # ================================
  # 📦 cht_ema_cognitive_tasks
  # ================================
  - title: "## 📦 cht_ema_cognitive_tasks — 🚀 Features"
    labels: [pkg:cognitive-tasks:feature]

  - title: "## 📦 cht_ema_cognitive_tasks — 🐞 Fixes"
    labels: [pkg:cognitive-tasks:fix]

  - title: "## 📦 cht_ema_cognitive_tasks — 🧪 Tests"
    labels: [pkg:cognitive-tasks:test]

  - title: "## 📦 cht_ema_cognitive_tasks — 🛠️ Improvements / Refactors"
    labels:
      [
        pkg:cognitive-tasks:improvement,
        pkg:cognitive-tasks:refactor,
        pkg:cognitive-tasks:perf,
      ]

  - title: "## 📦 cht_ema_cognitive_tasks — 📚 Documentation"
    labels: [pkg:cognitive-tasks:documentation]

  - title: "## 📦 cht_ema_cognitive_tasks — ⚙️ CI / Chores / Deps"
    labels:
      [
        pkg:cognitive-tasks:ci,
        pkg:cognitive-tasks:chore,
        pkg:cognitive-tasks:dependencies,
      ]

  - title: "## 📦 cht_ema_cognitive_tasks — ✨ Other changes"
    labels: [pkg:cognitive-tasks]

  # ================================
  # 📦 cht_ema_surveys
  # ================================
  - title: "## 📦 cht_ema_surveys — 🚀 Features"
    labels: [pkg:surveys:feature]

  - title: "## 📦 cht_ema_surveys — 🐞 Fixes"
    labels: [pkg:surveys:fix]

  - title: "## 📦 cht_ema_surveys — 🧪 Tests"
    labels: [pkg:surveys:test]

  - title: "## 📦 cht_ema_surveys — 🛠️ Improvements / Refactors"
    labels: [pkg:surveys:improvement, pkg:surveys:refactor, pkg:surveys:perf]

  - title: "## 📦 cht_ema_surveys — 📚 Documentation"
    labels: [pkg:surveys:documentation]

  - title: "## 📦 cht_ema_surveys — ⚙️ CI / Chores / Deps"
    labels: [pkg:surveys:ci, pkg:surveys:chore, pkg:surveys:dependencies]

  - title: "## 📦 cht_ema_surveys — ✨ Other changes"
    labels: [pkg:surveys]

    # ================================
    # 🧰 general (monorepo-wide)
    # ================================
  - title: "## 🧰 general"
    labels: [general]

change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"

exclude-labels:
  - skip-changelog
  - wip

version-resolver:
  major:
    labels: [breaking, "semver:major"]
  minor:
    labels: [feature, "semver:minor"]
  patch:
    labels:
      - fix
      - test
      - documentation
      - refactor
      - improvement
      - ci
      - chore
      - dependencies
      - perf
      - revert
      - general
      - "semver:patch"
  default: patch

autolabeler:
  - label: feature
    title: ["/^(feat|feature)\\b/i"]

  - label: fix
    title: ["/^(fix|bug)\\b/i"]

  - label: test
    title: ["/^(tests?)\\b/i"]

  - label: documentation
    title: ["/^(docs?|documentation)\\b/i"]

  - label: refactor
    title: ["/^(refactor)\\b/i"]

  - label: improvement
    title: ["/^(improve|improvement)\\b/i"]

  - label: perf
    title: ["/^(perf|performance)\\b/i"]

  - label: revert
    title: ["/^(revert)\\b/i"]

  - label: ci
    title: ["/^(ci)\\b/i"]

  - label: chore
    title: ["/^(chore)\\b/i"]

  - label: dependencies
    title: ["/^(deps?|dependencies)\\b/i"]

  - label: pkg:cognitive-tasks:feature
    title: ["/\\bpkg:cognitive-tasks:(feat|feature)\\b/i"]

  - label: pkg:cognitive-tasks:fix
    title: ["/\\bpkg:cognitive-tasks:(fix|bug)\\b/i"]

  - label: pkg:cognitive-tasks:test
    title: ["/\\bpkg:cognitive-tasks:(tests?)\\b/i"]

  - label: pkg:cognitive-tasks:improvement
    title: ["/\\bpkg:cognitive-tasks:(improve|improvement)\\b/i"]

  - label: pkg:cognitive-tasks:refactor
    title: ["/\\bpkg:cognitive-tasks:(refactor)\\b/i"]

  - label: pkg:cognitive-tasks:perf
    title: ["/\\bpkg:cognitive-tasks:(perf|performance)\\b/i"]

  - label: pkg:cognitive-tasks:documentation
    title: ["/\\bpkg:cognitive-tasks:(docs?|documentation)\\b/i"]

  - label: pkg:cognitive-tasks:ci
    title: ["/\\bpkg:cognitive-tasks:(ci)\\b/i"]

  - label: pkg:cognitive-tasks:chore
    title: ["/\\bpkg:cognitive-tasks:(chore)\\b/i"]

  - label: pkg:cognitive-tasks:dependencies
    title: ["/\\bpkg:cognitive-tasks:(deps?|dependencies)\\b/i"]

  - label: pkg:surveys:feature
    title: ["/\\bpkg:surveys:(feat|feature)\\b/i"]

  - label: pkg:surveys:fix
    title: ["/\\bpkg:surveys:(fix|bug)\\b/i"]

  - label: pkg:surveys:test
    title: ["/\\bpkg:surveys:(tests?)\\b/i"]

  - label: pkg:surveys:improvement
    title: ["/\\bpkg:surveys:(improve|improvement)\\b/i"]

  - label: pkg:surveys:refactor
    title: ["/\\bpkg:surveys:(refactor)\\b/i"]

  - label: pkg:surveys:perf
    title: ["/\\bpkg:surveys:(perf|performance)\\b/i"]

  - label: pkg:surveys:documentation
    title: ["/\\bpkg:surveys:(docs?|documentation)\\b/i"]

  - label: pkg:surveys:ci
    title: ["/\\bpkg:surveys:(ci)\\b/i"]

  - label: pkg:surveys:chore
    title: ["/\\bpkg:surveys:(chore)\\b/i"]

  - label: pkg:surveys:dependencies
    title: ["/\\bpkg:surveys:(deps?|dependencies)\\b/i"]

  - label: general
    title: ["/\\bgeneral\\b/i"]
