name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

template: |
  ## Changes
  $CHANGES

  ## Contributors
  $CONTRIBUTORS

categories:
  # ================================
  # 📦 cht_ema_cognitive_tasks
  # ================================
  - title: "## 📦 cht_ema_cognitive_tasks — 🚀 Features"
    labels: [pkg:cognitive-tasks:feature]

  - title: "## 📦 cht_ema_cognitive_tasks — 🐞 Fixes"
    labels: [pkg:cognitive-tasks:fix]

  - title: "## 📦 cht_ema_cognitive_tasks — 🧪 Tests"
    labels: [pkg:cognitive-tasks:test]

  - title: "## 📦 cht_ema_cognitive_tasks — 🛠️ Improvements / Refactors"
    labels:
      [
        pkg:cognitive-tasks:improvement,
        pkg:cognitive-tasks:refactor,
        pkg:cognitive-tasks:perf,
      ]

  - title: "## 📦 cht_ema_cognitive_tasks — 📚 Documentation"
    labels: [pkg:cognitive-tasks:documentation]

  - title: "## 📦 cht_ema_cognitive_tasks — ⚙️ CI / Chores / Deps"
    labels:
      [
        pkg:cognitive-tasks:ci,
        pkg:cognitive-tasks:chore,
        pkg:cognitive-tasks:dependencies,
      ]

  - title: "## 📦 cht_ema_cognitive_tasks — ✨ Other changes"
    labels: [pkg:cognitive-tasks]

  # ================================
  # 📦 cht_ema_surveys
  # ================================
  - title: "## 📦 cht_ema_surveys — 🚀 Features"
    labels: [pkg:surveys:feature]

  - title: "## 📦 cht_ema_surveys — 🐞 Fixes"
    labels: [pkg:surveys:fix]

  - title: "## 📦 cht_ema_surveys — 🧪 Tests"
    labels: [pkg:surveys:test]

  - title: "## 📦 cht_ema_surveys — 🛠️ Improvements / Refactors"
    labels: [pkg:surveys:improvement, pkg:surveys:refactor, pkg:surveys:perf]

  - title: "## 📦 cht_ema_surveys — 📚 Documentation"
    labels: [pkg:surveys:documentation]

  - title: "## 📦 cht_ema_surveys — ⚙️ CI / Chores / Deps"
    labels: [pkg:surveys:ci, pkg:surveys:chore, pkg:surveys:dependencies]

  - title: "## 📦 cht_ema_surveys — ✨ Other changes"
    labels: [pkg:surveys]

change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"

exclude-labels:
  - skip-changelog
  - wip

version-resolver:
  major:
    labels:
      - breaking
      - "semver:major"
  minor:
    labels:
      - feature
      - "semver:minor"
      - pkg:cognitive-tasks:feature
      - pkg:surveys:feature
  patch:
    labels:
      - fix
      - test
      - documentation
      - refactor
      - improvement
      - ci
      - chore
      - dependencies
      - perf
      - revert
      - "semver:patch"
      - pkg:cognitive-tasks:fix
      - pkg:cognitive-tasks:test
      - pkg:cognitive-tasks:documentation
      - pkg:cognitive-tasks:refactor
      - pkg:cognitive-tasks:improvement
      - pkg:cognitive-tasks:ci
      - pkg:cognitive-tasks:chore
      - pkg:cognitive-tasks:dependencies
      - pkg:cognitive-tasks:perf
      - pkg:cognitive-tasks:revert
      - pkg:surveys:fix
      - pkg:surveys:test
      - pkg:surveys:documentation
      - pkg:surveys:refactor
      - pkg:surveys:improvement
      - pkg:surveys:ci
      - pkg:surveys:chore
      - pkg:surveys:dependencies
      - pkg:surveys:perf
      - pkg:surveys:revert
  default: patch

autolabeler:
  # type-package compound labels: cognitive-tasks
  - label: pkg:cognitive-tasks:feature
    title: ['/^(feature|feat)\(cognitive-tasks\):/i']

  - label: pkg:cognitive-tasks:fix
    title: ['/^(fix|bug)\(cognitive-tasks\):/i']

  - label: pkg:cognitive-tasks:test
    title: ['/^(test|tests)\(cognitive-tasks\):/i']

  - label: pkg:cognitive-tasks:documentation
    title: ['/^(doc|docs|documentation)\(cognitive-tasks\):/i']

  - label: pkg:cognitive-tasks:refactor
    title: ['/^(refactor)\(cognitive-tasks\):/i']

  - label: pkg:cognitive-tasks:improvement
    title: ['/^(improve|improvement)\(cognitive-tasks\):/i']

  - label: pkg:cognitive-tasks:perf
    title: ['/^(perf|performance)\(cognitive-tasks\):/i']

  - label: pkg:cognitive-tasks:ci
    title: ['/^(ci)\(cognitive-tasks\):/i']

  - label: pkg:cognitive-tasks:chore
    title: ['/^(chore)\(cognitive-tasks\):/i']

  - label: pkg:cognitive-tasks:dependencies
    title: ['/^(deps|dependencies)\(cognitive-tasks\):/i']

  # type-package compound labels: surveys
  - label: pkg:surveys:feature
    title: ['/^(feature|feat)\(surveys\):/i']

  - label: pkg:surveys:fix
    title: ['/^(fix|bug)\(surveys\):/i']

  - label: pkg:surveys:test
    title: ['/^(test|tests)\(surveys\):/i']

  - label: pkg:surveys:documentation
    title: ['/^(docs|doc|documentation)\(surveys\):/i']

  - label: pkg:surveys:refactor
    title: ['/^(refactor)\(surveys\):/i']

  - label: pkg:surveys:improvement
    title: ['/^(improve|improvement)\(surveys\):/i']

  - label: pkg:surveys:perf
    title: ['/^(perf|performance)\(surveys\):/i']

  - label: pkg:surveys:ci
    title: ['/^(ci)\(surveys\):/i']

  - label: pkg:surveys:chore
    title: ['/^(chore)\(surveys\):/i']

  - label: pkg:surveys:dependencies
    title: ['/^(deps|dependencies)\(surveys\):/i']

  # monorepo-wide "general" (no package)
  - label: general
    title:
      [
        '/^(feature|feat)\(general\):/i',
        '/^(fix|bug)\(general\):/i',
        '/^(test|tests)\(general\):/i',
        '/^(doc|docs|documentation)\(general\):/i',
        '/^(refactor)\(general\):/i',
        '/^(improve|improvement)\(general\):/i',
        '/^(perf|performance)\(general\):/i',
        '/^(revert)\(general\):/i',
        '/^(ci)\(general\):/i',
        '/^(chore)\(general\):/i',
        '/^(deps|dependencies)\(general\):/i',
      ]

  # basic labels if nothing more specific matches
  - label: feature
    title: ['/^(feature|feat)\([^)]*\):/i']

  - label: fix
    title: ['/^(fix|bug)\([^)]*\):/i']

  - label: test
    title: ['/^(test|tests)\([^)]*\):/i']

  - label: documentation
    title: ['/^(docs|doc|documentation)\([^)]*\):/i']

  - label: refactor
    title: ['/^(refactor)\([^)]*\):/i']

  - label: improvement
    title: ['/^(improve|improvement)\([^)]*\):/i']

  - label: perf
    title: ['/^(perf|performance)\([^)]*\):/i']

  - label: revert
    title: ['/^(revert)\([^)]*\):/i']

  - label: ci
    title: ['/^(ci)\([^)]*\):/i']

  - label: chore
    title: ['/^(chore)\([^)]*\):/i']

  - label: dependencies
    title: ['/^(deps|dependencies)\([^)]*\):/i']
