autolabeler:
  # -------- Generic type labels (any scope) --------
  - label: feature
    title: ["/^(feature|feat)\\([^)]*\\):/i"]

  - label: fix
    title: ["/^(fix|bug)\\([^)]*\\):/i"]

  - label: test
    title: ["/^(test|tests)\\([^)]*\\):/i"]

  - label: documentation
    title: ["/^(docs|doc|documentation)\\([^)]*\\):/i"]

  - label: refactor
    title: ["/^(refactor)\\([^)]*\\):/i"]

  - label: improvement
    title: ["/^(improve|improvement)\\([^)]*\\):/i"]

  - label: perf
    title: ["/^(perf|performance)\\([^)]*\\):/i"]

  - label: revert
    title: ["/^(revert)\\([^)]*\\):/i"]

  - label: ci
    title: ["/^(ci)\\([^)]*\\):/i"]

  - label: chore
    title: ["/^(chore)\\([^)]*\\):/i"]

  - label: dependencies
    title: ["/^(deps|dependencies)\\([^)]*\\):/i"]

  # -------- Package-scoped labels: cognitive-tasks --------
  - label: pkg:cognitive-tasks:feature
    title: ["/^(feature|feat)\\(cognitive-tasks\\):/i"]

  - label: pkg:cognitive-tasks:fix
    title: ["/^(fix|bug)\\(cognitive-tasks\\):/i"]

  - label: pkg:cognitive-tasks:test
    title: ["/^(test|tests)\\(cognitive-tasks\\):/i"]

  - label: pkg:cognitive-tasks:documentation
    title: ["/^(docs|doc|documentation)\\(cognitive-tasks\\):/i"]

  - label: pkg:cognitive-tasks:refactor
    title: ["/^(refactor)\\(cognitive-tasks\\):/i"]

  - label: pkg:cognitive-tasks:improvement
    title: ["/^(improve|improvement)\\(cognitive-tasks\\):/i"]

  - label: pkg:cognitive-tasks:perf
    title: ["/^(perf|performance)\\(cognitive-tasks\\):/i"]

  - label: pkg:cognitive-tasks:ci
    title: ["/^(ci)\\(cognitive-tasks\\):/i"]

  - label: pkg:cognitive-tasks:chore
    title: ["/^(chore)\\(cognitive-tasks\\):/i"]

  - label: pkg:cognitive-tasks:dependencies
    title: ["/^(deps|dependencies)\\(cognitive-tasks\\):/i"]

  # -------- Package-scoped labels: surveys --------
  - label: pkg:surveys:feature
    title: ["/^(feature|feat)\\(surveys\\):/i"]

  - label: pkg:surveys:fix
    title: ["/^(fix|bug)\\(surveys\\):/i"]

  - label: pkg:surveys:test
    title: ["/^(test|tests)\\(surveys\\):/i"]

  - label: pkg:surveys:documentation
    title: ["/^(docs|doc|documentation)\\(surveys\\):/i"]

  - label: pkg:surveys:refactor
    title: ["/^(refactor)\\(surveys\\):/i"]

  - label: pkg:surveys:improvement
    title: ["/^(improve|improvement)\\(surveys\\):/i"]

  - label: pkg:surveys:perf
    title: ["/^(perf|performance)\\(surveys\\):/i"]

  - label: pkg:surveys:ci
    title: ["/^(ci)\\(surveys\\):/i"]

  - label: pkg:surveys:chore
    title: ["/^(chore)\\(surveys\\):/i"]

  - label: pkg:surveys:dependencies
    title: ["/^(deps|dependencies)\\(surveys\\):/i"]

  # -------- Monorepo-wide "general" (no package) --------
  - label: general
    title:
      [
        "/^(feature|feat)\\(general\\):/i",
        "/^(fix|bug)\\(general\\):/i",
        "/^(test|tests)\\(general\\):/i",
        "/^(docs|doc|documentation)\\(general\\):/i",
        "/^(refactor)\\(general\\):/i",
        "/^(improve|improvement)\\(general\\):/i",
        "/^(perf|performance)\\(general\\):/i",
        "/^(revert)\\(general\\):/i",
        "/^(ci)\\(general\\):/i",
        "/^(chore)\\(general\\):/i",
        "/^(deps|dependencies)\\(general\\):/i",
      ]
