name: cht_ema
publish_to: none
environment:
  sdk: ^3.9.0

workspace:
  - packages/cht_ema_surveys
  - packages/cht_ema_surveys/example
  - packages/cht_cognition
  - packages/cht_cognition/example
  - apps/mhealthgoal

dev_dependencies:
  build_runner: ^2.10.4
  freezed: ^3.2.5
  json_serializable: ^6.13.2
  melos: ^7.1.1
  rename: ^3.1.0
  very_good_analysis: ^10.0.0

melos:
  scripts:
    check_format:
      run: dart run melos exec dart format --set-exit-if-changed .
      description: "Check if any file in any package needs formatting. Convenient for CI checks."

    analyze:
      run: dart run melos exec flutter analyze --fatal-infos --fatal-warnings
      description: "Run static code analysis in all packages."

    test:
      description: "Run unit tests in all packages and their example apps."
      steps:
        - dart run melos exec --dir-exists=test -- flutter test --no-pub
        - dart run melos exec --dir-exists=example -- 'cd example && flutter test --no-pub'

    generate_localizations:
      description: "Generate localization files for all packages and their examples apps."
      steps:
        - dart run melos exec -- 'flutter gen-l10n'

    build_android_examples:
      run: dart run melos exec -c 1 --dir-exists=example -- 'cd example && flutter build apk --debug'
      description: "Check Android APKs build for all example apps. Useful for CI checks."

    build_ios_examples:
      run: dart run melos exec -c 2 --dir-exists=example -- 'cd example && flutter build ios --no-codesign'
      description: "Check iOS app build for all example apps. Useful for CI checks."

    build_ios_mhealthgoal:
      run: dart run melos exec -c 1 --scope=mhealthgoal -- 'flutter build ios --no-codesign'
      description: "Check iOS mHealthGoal app builds. Useful for CI checks."

    build_android_mhealthgoal:
      run: dart run melos exec -c 1 --scope=mhealthgoal -- 'flutter build apk --debug'
      description: "Check Android mHealthGoal app builds. Useful for CI checks."

    all_basic_checks:
      run: |
        dart run melos bootstrap && 
        dart run melos run generate_localizations && 
        dart run melos run check_format &&
        dart run  melos run analyze &&
        dart run  melos run test
      description: "Run all basic checks: bootstrap, generate localizations, check format, analyze, and test."

    all_formal_checks:
      run: |
        dart run melos bootstrap && 
        dart run melos run generate_localizations && 
        dart run melos run check_format && 
        dart run  melos run analyze && 
        dart run  melos run test && 
        dart run melos run build_android_examples && 
        dart run melos run build_ios_examples
      description: "Run all formal checks: bootstrap, generate localizations, check format, analyze, test, build android, build ios."
dependencies:
  firebase_core: ^4.7.0
  firebase_messaging: ^16.2.0
  flutter_local_notifications: ^20.1.0
  freezed_annotation: ^3.1.0
