arb-dir: lib/src/core/l10n
output-class: ChtCognitionLocalization
template-arb-file: package_en.arb
output-localization-file: cht_cognition_localization.dart
output-dir: lib/src/core/l10n/generated
nullable-getter: false
