name: CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    analyze_and_test:
        name: Analyze & Test
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v4

            - name: Cache Pub packages
              uses: actions/cache@v4
              with:
                  path: ~/.pub-cache
                  key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock', 'packages/**/pubspec.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-pub-

            - name: Setup Flutter
              uses: subosito/flutter-action@v2.19.0
              with:
                  channel: stable
                  flutter-version: 3.35.5
                  cache: true

            - name: Setup Melos
              uses: bluefireteam/melos-action@v3

            - name: Check formatting (Melos)
              run: dart run melos run check_format

            - name: Analyze (Melos)
              run: dart run melos run analyze

            - name: Test (Melos)
              run: dart run melos run test

    android_build:
        name: Build Android examples
        runs-on: ubuntu-latest
        needs: analyze_and_test
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Cache Pub packages
              uses: actions/cache@v4
              with:
                  path: ~/.pub-cache
                  key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock', 'packages/**/pubspec.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-pub-

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: "17"

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  cache: true
                  flutter-version: 3.35.5

            - name: Bootstrap Melos workspace
              run: |
                  flutter pub get
                  dart run melos bootstrap

            - name: Build Android APKs (Melos)
              run: dart run melos run build_android_examples

    ios_build:
        name: Build iOS examples (no codesign)
        runs-on: macos-latest
        needs: analyze_and_test
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Cache Pub packages
              uses: actions/cache@v4
              with:
                  path: ~/.pub-cache
                  key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock', 'packages/**/pubspec.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-pub-

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  cache: true
                  flutter-version: 3.35.5

            - name: Bootstrap Melos workspace
              run: |
                  flutter pub get
                  dart run melos bootstrap

            - name: Build iOS apps (Melos)
              run: dart run melos run build_ios_examples
